### ISSUE TITLE
website outdated

### ISSUE THREAD

**Issue by cwittmer** [siwapp/siwapp-sf3#12]
Hi
the website is outdated and is telling about siwapp-sf1 (0.4.2beta) as current version.
same for Installation Guide.
Will someone please be so kind and update the information ?

What is the correct current version to use ?
How to update to current version ?

Thank you

**Comment by ParisLiakos** [comment]
Unfortunately i dont have access to the website information. I am pretty sure that the general direction will be towards the ruby on rails from the official team.
But i cant say tbh..This version is something i maintain by myself and in parallel, probably targeting people that cant run the ruby version for one reason or another. The old 0.4.2beta version is discontinued, you can either upgrade to this project or the ruby one. The decision is up to you, but neither one is stable

**Comment by cwittmer** [comment]
Thank you for the information ... this is bringing more light into this strange darkness.
TBH I have no understanding for having a stable/discontinued version ... this is unreliable :-1:

**Comment by ParisLiakos** [comment]
Yeap, i know, thats why i had to do this "fork/port" in the first place..Because the old version does not work with php7.
Other than that i am not sure about the project's vision atm, but i also dont wish to maintain this project myself, thats why keeping this one under the siwapp namespace is for the best imo.
