### ISSUE TITLE
Shared hosting compatibility

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#13]
The legacy siwapp PHP version runs on shared hosting.

I think the only thing stopping the new sf3 version from it is the need for wkhtmltopdf. Maybe it could be replaced by another pdf generator?

**Comment by ParisLiakos** [comment]
Maybe we could have dompdf or tcpdf as alternative, but if i remember correctly there is a static version of wkhtmltopdf that you could try on a shared hosting..

**Comment by JMCA2** [comment]
I was able to install wkhtmltopdf on shared hosting by following the steps here: http://stackoverflow.com/a/3116571 and editing the binary path file con config.php

Maybe this could by added to the install instructions somewhere.

**Comment by ParisLiakos** [comment]
Thanks for your feedback!

It looks like there is also the alternative of shipping the binaries with siwapp:
https://github.com/KnpLabs/snappy#wkhtmltopdf-binary-as-composer-dependencies

But i am not sure thats a good idea. It definitely needs some documentation, since there are many solutions to that.
