### ISSUE TITLE
Docs: Change /web/ URL

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#50]
I think it makes more sense if the app worked from "/" by default instead or requiring to visit "/web/"

**Comment by ParisLiakos** [comment]
You should make your document root in your virtualhost point to the web folder.
If you do not have access to the virtual host configuration you can do something like this:
https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-web-directory
and rename the folder according to your control panel/shared host naming conventions, and then use this folder as root.

That is made so that only the absolutely required files are exposed to the internet (web folder) and nothing more than that, which leads to better security. That way lets say your config files are not accessible.

**Comment by JMCA2** [comment]
Ok thank you!

Maybe this is something that could be added to the documentation? So people not familiar with the symfony structure installing the app know about it? And don't expose their config files.

**Comment by ParisLiakos** [comment]
Sure, good point. I will put it in the wiki, the readme got too big :)
So, i ll just reopen this and leave it open until wiki is there

**Comment by ParisLiakos** [comment]
Created https://github.com/siwapp/siwapp-sf3/wiki/The-web-folder
Cheers

**Comment by JMCA2** [comment]
Nice! Thank you! :)
